### ISSUE TITLE
Fix provider mapping in trainings & IG full update 

### ISSUE THREAD

**Issue by Michal-Kolomanski** [cyfronet-fid/eosc-search-service#1317] opened 2024-05-14 11:28 UTC
From 25.04.2024 10:30 - Full updates of trainings and IGs are failing.

Scope:
- [x] investigate the reason. Is the reason that some production instances got shut down? 
- [x] fix the issue 

Example:
http://149.156.10.242:5555/task/0a789a17-6bfc-4017-ba33-b8bc9ff8b92d

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/tasks/batch.py", line 38, in transform_batch
    df_trans = transformer(spark)(df)
  File "/app/transform/transformers/base/base.py", line 44, in __call__
    df = self.apply_complex_trans(df)
  File "/app/transform/transformers/training.py", line 82, in apply_complex_trans
    df = self.map_providers_and_orgs(df)
  File "/app/transform/transformers/training.py", line 353, in map_providers_and_orgs
    providers_mapping = get_providers_mapping()
  File "/app/services/mp_pc/data.py", line 102, in get_providers_mapping
    return {provider["pid"]: provider["name"] for provider in providers_raw}
TypeError: 'NoneType' object is not iterable
```

**Comment by wiktorflorian** [comment] 2024-05-16 11:24
The issue is caused by the closing of the production instance (the request to the beta instance returns values). After the request to the production instance, we receive HTML information about the next phase of EOSC. This results in the `requests.RequestException`, which in turn causes our function get_data() to return None which is not iterable. Tis is the reason for the error.

Due to the lack of other sources of provider PIDs at the moment, I am currently focusing on resolving the issue with None not being iterable. This is achieved by having `get_providers_mapping()` return an error and an empty dict in such a case.

**Closed** 2024-05-16 12:30 UTC
Labels: bug, transformer
